trigger:
- main

pool:
  name: 'Default'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'install npm dependencies'

- script: npm run test:unit
  displayName: 'run unit tests'
